// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqnXoh8C8LVDaGHJIupCy1VZ3PVmDvj8A',
    appId: '1:146467001660:web:3adc8fda65c427511eba39',
    messagingSenderId: '146467001660',
    projectId: 'chat-app-551ec',
    authDomain: 'chat-app-551ec.firebaseapp.com',
    storageBucket: 'chat-app-551ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3IowRCrZ070-D3Xp4-SIKnN58APMf41c',
    appId: '1:146467001660:android:3fcd07e54498e5ba1eba39',
    messagingSenderId: '146467001660',
    projectId: 'chat-app-551ec',
    storageBucket: 'chat-app-551ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp3ye-nToLTje0zg4iq3_-h0-IqiLi96Q',
    appId: '1:146467001660:ios:414155834b6f7dcf1eba39',
    messagingSenderId: '146467001660',
    projectId: 'chat-app-551ec',
    storageBucket: 'chat-app-551ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp3ye-nToLTje0zg4iq3_-h0-IqiLi96Q',
    appId: '1:146467001660:ios:414155834b6f7dcf1eba39',
    messagingSenderId: '146467001660',
    projectId: 'chat-app-551ec',
    storageBucket: 'chat-app-551ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqnXoh8C8LVDaGHJIupCy1VZ3PVmDvj8A',
    appId: '1:146467001660:web:67ff2c7d019103801eba39',
    messagingSenderId: '146467001660',
    projectId: 'chat-app-551ec',
    authDomain: 'chat-app-551ec.firebaseapp.com',
    storageBucket: 'chat-app-551ec.firebasestorage.app',
  );
}
